import { useMemo, useState } from 'react'
import { isDone, today, uid } from '../lib/storage.js'

const clientName = client => client?.razao || client?.nome || client?.fantasia || 'Cliente'
function Empty({ children = 'Nenhum registro.' }) { return <div className="empty">{children}</div> }
function Modal({ title, children, onClose }) { return <div className="modal"><div className="modal-card"><header><h2>{title}</h2><button onClick={onClose}>×</button></header>{children}</div></div> }
function Field({ label, children }) { return <label className="field"><span>{label}</span>{children}</label> }

export function Clients({ office, update }) {
  const [editing, setEditing] = useState(null), [query, setQuery] = useState('')
  const rows = office.clients.filter(x => `${clientName(x)} ${x.documento || ''}`.toLowerCase().includes(query.toLowerCase()))
  function save(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); update(d => { const row = { ...editing, id: editing?.id || uid('cli'), razao: data.razao, documento: data.documento, tributacao: data.tributacao, departamentos: data.departamentos.split(',').map(x => x.trim()).filter(Boolean), status: data.status, relacionamento: data.relacionamento }; d.clients = editing ? d.clients.map(x => x.id === editing.id ? row : x) : [...d.clients, row] }); setEditing(null) }
  return <Module title="Clientes" action="Novo cliente" onAction={() => setEditing({})}><input className="search" placeholder="Buscar cliente ou CPF/CNPJ" value={query} onChange={e => setQuery(e.target.value)} /><div className="table"><div className="tr head"><span>Cliente</span><span>Documento</span><span>Tributação</span><span>Status</span><span /></div>{rows.map(x => <div className="tr" key={x.id}><b>{clientName(x)}</b><span>{x.documento || '—'}</span><span>{x.tributacao || '—'}</span><span>{x.status || 'Ativo'}</span><button onClick={() => setEditing(x)}>Editar</button></div>)}</div>{!rows.length && <Empty />}{editing && <Modal title={editing.id ? 'Editar cliente' : 'Novo cliente'} onClose={() => setEditing(null)}><form className="form" onSubmit={save}><Field label="Razão social"><input name="razao" defaultValue={editing.razao} required /></Field><Field label="CPF/CNPJ"><input name="documento" defaultValue={editing.documento} /></Field><Field label="Tributação"><input name="tributacao" defaultValue={editing.tributacao} /></Field><Field label="Departamentos"><input name="departamentos" defaultValue={(editing.departamentos || []).join(', ')} placeholder="Fiscal, Contábil" /></Field><Field label="Relacionamento"><select name="relacionamento" defaultValue={editing.relacionamento || 'Recorrente'}><option>Recorrente</option><option>Avulso</option></select></Field><Field label="Status"><select name="status" defaultValue={editing.status || 'Ativo'}><option>Ativo</option><option>Inativo</option></select></Field><button className="primary">Salvar</button></form></Modal>}</Module>
}

export function Tasks({ office, update }) {
  const [editing, setEditing] = useState(null); const clients = new Map(office.clients.map(x => [String(x.id), clientName(x)]))
  function save(event) { event.preventDefault(); const f = Object.fromEntries(new FormData(event.currentTarget)); update(d => { const row = { ...editing, id: editing?.id || uid('tar'), titulo: f.titulo, clientId: f.clientId, departamento: f.departamento, responsavel: f.responsavel, prazo: f.prazo, prioridade: f.prioridade, status: f.status, recorrencia: f.recorrencia, descricao: f.descricao, subtarefas: editing?.subtarefas || [], updatedAt: new Date().toISOString() }; d.tasks = editing ? d.tasks.map(x => x.id === editing.id ? row : x) : [...d.tasks, row] }); setEditing(null) }
  return <Module title="Tarefas" action="Nova tarefa" onAction={() => setEditing({})}><div className="cards">{office.tasks.map(x => <article className="record" key={x.id}><div><span className="kind task">Tarefa</span><b>{x.titulo}</b><small>{clients.get(String(x.clientId)) || 'Interna'} · {x.departamento || 'Sem departamento'} · {x.prazo || 'Sem prazo'}</small></div><div><button className={isDone(x.status) ? '' : 'primary'} onClick={() => update(d => { const row = d.tasks.find(t => t.id === x.id); row.status = isDone(row.status) ? 'Pendente' : 'Concluída' })}>{isDone(x.status) ? 'Reabrir' : 'Concluir'}</button><button onClick={() => setEditing(x)}>Editar</button></div></article>)}</div>{!office.tasks.length && <Empty />}{editing && <Modal title={editing.id ? 'Editar tarefa' : 'Nova tarefa'} onClose={() => setEditing(null)}><form className="form" onSubmit={save}><Field label="Título"><input name="titulo" defaultValue={editing.titulo} required /></Field><Field label="Cliente"><select name="clientId" defaultValue={editing.clientId || ''}><option value="">Interna</option>{office.clients.filter(x => x.status !== 'Inativo').map(x => <option value={x.id} key={x.id}>{clientName(x)}</option>)}</select></Field><Field label="Departamento"><input name="departamento" defaultValue={editing.departamento} /></Field><Field label="Responsável"><input name="responsavel" defaultValue={editing.responsavel} /></Field><Field label="Prazo"><input type="date" name="prazo" defaultValue={editing.prazo} /></Field><Field label="Prioridade"><select name="prioridade" defaultValue={editing.prioridade || 'Normal'}><option>Baixa</option><option>Normal</option><option>Alta</option><option>Urgente</option></select></Field><Field label="Status"><select name="status" defaultValue={editing.status || 'Pendente'}><option>Pendente</option><option>Em andamento</option><option>Aguardando cliente</option><option>Concluída</option></select></Field><Field label="Recorrência"><select name="recorrencia" defaultValue={editing.recorrencia || ''}><option value="">Não recorrente</option><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option></select></Field><Field label="Descrição"><textarea name="descricao" defaultValue={editing.descricao} /></Field><button className="primary">Salvar</button></form></Modal>}</Module>
}

export function Processes({ office, update }) {
  const [editing, setEditing] = useState(null); const clients = new Map(office.clients.map(x => [String(x.id), clientName(x)]))
  function save(event) { event.preventDefault(); const f = Object.fromEntries(new FormData(event.currentTarget)); update(d => { const row = { ...editing, id: editing?.id || uid('proc'), tipo: f.tipo, clientId: f.clientId, prazoFinal: f.prazoFinal, status: f.status, dataAbertura: editing?.dataAbertura || today(), observacoes: f.observacoes, etapas: editing?.etapas || [], protocolos: editing?.protocolos || [] }; d.processes = editing ? d.processes.map(x => x.id === editing.id ? row : x) : [...d.processes, row] }); setEditing(null) }
  return <Module title="Processos" action="Novo processo" onAction={() => setEditing({})}><div className="cards">{office.processes.map(x => <article className="record" key={x.id}><div><span className="kind process">Processo</span><b>{x.tipo}</b><small>{clients.get(String(x.clientId)) || 'Cliente'} · {x.status} · {x.prazoFinal || 'Sem prazo'}</small></div><div><button className={isDone(x.status) ? '' : 'primary'} onClick={() => update(d => { const row = d.processes.find(p => p.id === x.id); row.status = isDone(row.status) ? 'Em andamento' : 'Concluído'; row.dataConclusao = isDone(row.status) ? today() : '' })}>{isDone(x.status) ? 'Reabrir' : 'Concluir'}</button><button onClick={() => setEditing(x)}>Editar</button></div></article>)}</div>{!office.processes.length && <Empty />}{editing && <Modal title={editing.id ? 'Editar processo' : 'Novo processo'} onClose={() => setEditing(null)}><form className="form" onSubmit={save}><Field label="Tipo"><input name="tipo" defaultValue={editing.tipo} required /></Field><Field label="Cliente"><select name="clientId" defaultValue={editing.clientId || ''} required><option value="">Selecione</option>{office.clients.filter(x => x.status !== 'Inativo').map(x => <option value={x.id} key={x.id}>{clientName(x)}</option>)}</select></Field><Field label="Prazo"><input type="date" name="prazoFinal" defaultValue={editing.prazoFinal} /></Field><Field label="Status"><select name="status" defaultValue={editing.status || 'Novo'}><option>Novo</option><option>Em andamento</option><option>Aguardando cliente</option><option>Aguardando órgão</option><option>Concluído</option></select></Field><Field label="Observações"><textarea name="observacoes" defaultValue={editing.observacoes} /></Field><button className="primary">Salvar</button></form></Modal>}</Module>
}

export function Obligations({ office, update }) {
  const [creating, setCreating] = useState(false); const clients = new Map(office.clients.map(x => [String(x.id), clientName(x)]))
  function save(event) { event.preventDefault(); const f = Object.fromEntries(new FormData(event.currentTarget)); update(d => d.obligations.push({ id: uid('obr'), nome: f.nome, categoria: f.categoria, competencia: f.competencia, clientes: f.clientId ? [{ clienteId: f.clientId, status: 'Pendente', vencimento: f.vencimento, concluidoEm: '' }] : [] })); setCreating(false) }
  return <Module title="Obrigações" action="Nova obrigação" onAction={() => setCreating(true)}><div className="cards">{office.obligations.flatMap(o => (o.clientes || []).map(x => <article className="record" key={`${o.id}-${x.clienteId}`}><div><span className="kind obligation">Obrigação</span><b>{o.nome}</b><small>{clients.get(String(x.clienteId)) || 'Cliente'} · {o.categoria} · {x.vencimento || 'Sem prazo'}</small></div><button className={isDone(x.status) ? '' : 'primary'} onClick={() => update(d => { const row = d.obligations.find(z => z.id === o.id).clientes.find(z => z.clienteId === x.clienteId); row.status = isDone(row.status) ? 'Pendente' : 'Concluída'; row.concluidoEm = isDone(row.status) ? today() : '' })}>{isDone(x.status) ? 'Reabrir' : 'Concluir'}</button></article>))}</div>{!office.obligations.length && <Empty />}{creating && <Modal title="Nova obrigação" onClose={() => setCreating(false)}><form className="form" onSubmit={save}><Field label="Nome"><input name="nome" required /></Field><Field label="Categoria"><input name="categoria" defaultValue="Fiscal" /></Field><Field label="Competência"><input name="competencia" type="month" /></Field><Field label="Cliente inicial"><select name="clientId"><option value="">Sem vínculo inicial</option>{office.clients.filter(x => x.status !== 'Inativo').map(x => <option value={x.id} key={x.id}>{clientName(x)}</option>)}</select></Field><Field label="Vencimento"><input name="vencimento" type="date" /></Field><button className="primary">Salvar</button></form></Modal>}</Module>
}

export function Calendar({ office }) {
  const clients = new Map(office.clients.map(x => [String(x.id), clientName(x)])); const events = useMemo(() => [...office.tasks.filter(x => x.prazo).map(x => ({ date: x.prazo, type: 'Tarefa', title: x.titulo, client: clients.get(String(x.clientId)) || 'Interna', done: isDone(x.status) })), ...office.processes.filter(x => x.prazoFinal).map(x => ({ date: x.prazoFinal, type: 'Processo', title: x.tipo, client: clients.get(String(x.clientId)) || 'Cliente', done: isDone(x.status) })), ...office.obligations.flatMap(o => (o.clientes || []).filter(x => x.vencimento).map(x => ({ date: x.vencimento, type: 'Obrigação', title: o.nome, client: clients.get(String(x.clienteId)) || 'Cliente', done: isDone(x.status) })))].sort((a,b) => a.date.localeCompare(b.date)), [office, clients])
  return <Module title="Calendário"><div className="timeline">{events.map((x, i) => <article className={x.done ? 'done' : ''} key={`${x.type}-${i}`}><time>{new Date(`${x.date}T00:00:00`).toLocaleDateString('pt-BR')}</time><div><b>{x.type} · {x.title}</b><small>{x.client}</small></div></article>)}</div>{!events.length && <Empty />}</Module>
}

export function Finance({ office, update }) { const total = office.finance.filter(x => !['Recebido','Cancelado'].includes(x.status)).reduce((a,x) => a + Number(x.valor || 0), 0); return <Module title="Financeiro"><div className="kpis"><div className="kpi"><span>Em aberto</span><strong>{total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong></div><div className="kpi"><span>Lançamentos</span><strong>{office.finance.length}</strong></div></div><div className="cards">{office.finance.map(x => <article className="record" key={x.id}><div><b>{x.descricao || 'Honorário'}</b><small>{x.cliente || 'Cliente'} · {x.vencimento || 'Sem vencimento'}</small></div><select value={x.status} onChange={e => update(d => { d.finance.find(z => z.id === x.id).status = e.target.value })}><option>Pendente</option><option>Recebido</option><option>Atrasado</option><option>Cancelado</option></select></article>)}</div></Module> }

export function Settings({ office, update }) { function save(e) { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); update(d => Object.assign(d.settings, f)) } return <Module title="Configurações"><form className="form panel" onSubmit={save}><Field label="Nome do escritório"><input name="office" defaultValue={office.settings.office} /></Field><Field label="Nome do sistema"><input name="system" defaultValue={office.settings.system} /></Field><Field label="Usuário"><input name="user" defaultValue={office.settings.user} /></Field><Field label="Cargo"><input name="role" defaultValue={office.settings.role} /></Field><button className="primary">Salvar personalização</button></form><section className="panel"><h2>Compatibilidade</h2><p>Todos os dados continuam nas chaves <b>med_*</b>. Modelos de tarefas: {office.taskTemplates.length}. Modelos de processos: {office.processModels.length}. Histórico: {office.history.length} eventos.</p></section></Module> }

function Module({ title, action, onAction, children }) { return <><div className="page-head"><div><h1>{title}</h1><p>Meu Escritório Digital V11.1</p></div>{action ? <button className="primary" onClick={onAction}>+ {action}</button> : null}</div>{children}</> }
